apiVersion : apps/v1
kind: Deployment
metadata:
  name: wesleicorinthians 
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: wesleicorinthians
  template:
    metadata:
      labels:
        app: wesleicorinthians 
        
    spec:
      containers:
        - name: wesleicorinthians 
          image: wesleidevops.azurecr.io/wesleicorinthians
           env:
            - name: SQLALCHEMY_DATABASE_URI
              value: "mysql+pymysql://jaine:uis71VCal07@179.188.38.79:3306/jaine"
            - name: REDISTOGO_URL
              value: "redis://179.188.38.79:6379"
          ports:
          - containerPort: 5000
