apiVersion : apps/v1
kind: Deployment
metadata:
  name: wesleivarjaodesafio6 
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wesleivarjaodesafio6 
  template:
    metadata:
      labels:
        app: wesleivarjaodesafio6 
        
    spec:
      containers:
        - name: wesleivarjaodesafio6 
          image: wesleidevops.azurecr.io/wesleivarjaodesafio6
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: "mysql+pymysql://jaine:uis71VCal07@179.188.38.79:3306/jaine"
            - name: REDISTOGO_URL
              value: "redis://179.188.38.79:6379"
          ports:
          - containerPort: 5000
