apiVersion : apps/v1
kind: Deployment
metadata:
  name: wesleivarjaodesafio 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wesleivarjaodesafio 
  template:
    metadata:
      labels:
        app: wesleivarjaodesafio 
    spec:
      containers:
        - name: wesleivarjaodesafio 
          image: desafio06.azurecr.io/wesleivarjaodesafio
          ports:
          - containerPort: 5000
