apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: wesleivarjaodesafio60 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wesleivarjaodesafio60 
    spec:
      containers:
        - name: wesleivarjaodesafio60 
          image: wesleidevops.azurecr.io/wesleivarjaodesafio60
          ports:
          - containerPort: 5000