apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: wesleicorinthians 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wesleicorinthians 
    spec:
      containers:
        - name: wesleicorinthians 
          image: wesleidevops.azurecr.io/wesleicorinthians
          ports:
          - containerPort: 5000