apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: wesleidesafio06 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wesleidesafio06 
    spec:
      containers:
        - name: wesleidesafio06 
          image: wesleidevops.azurecr.io/wesleidesafio06
          ports:
          - containerPort: 5000