apiVersion : apps/v1
kind: Deployment
metadata:
  name: wesleidesafio06 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wesleidesafio06
  template:
    metadata:
      labels:
        app: wesleidesafio06 
    spec:
      containers:
        - name: wesleidesafio06 
          image: wesleidevops.azurecr.io/wesleidesafio06
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: "mysql+pymysql://jaine:uis71VCal07@179.188.38.79:3306/jaine"
            - name: REDISTOGO_URL
              value: "redis://179.188.38.79:6379"
          ports:
          - containerPort: 5000
