apiVersion: v1
kind: Service
metadata:
  labels:
    app: health 
  name: health-service
  namespace: default
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP    
  type: LoadBalancer
  selector:
    app: health
