apiVersion: v1
kind: Service
metadata:
    name: wesleivarjaodesafio
    namespace: default
spec:
    type: LoadBalancer
    ports:
    - port: 5001 
    selector:
        app: wesleivarjaodesafio
