apiVersion: v1
kind: Service
metadata:
 labels: 
    app: wesleivarjaodesafio
 name: wesleivarjaodesafio-services
 namespace: default
 
spec:
    type: LoadBalancer
    ports:
    - port: 5000 
    selector:
        app: wesleivarjaodesafio
