apiVersion: v1
kind: Service
metadata:
  labels: 
    app: weschapdesafio06
  name: weschapdesafio06-service
  namespace: desafio06
 
spec:
  type: LoadBalancer
  ports:
    - port: 5000 
  selector:
    app: weschapdesafio06
