apiVersion: v1
kind: Service
metadata:
    name: wesleivarjaodesafio60
    namespace: default
spec:
    type: LoadBalancer
    ports:
    - port: 5000 
    selector:
        app: wesleivarjaodesafio60
