apiVersion: v1
kind: Service
metadata:
  labels: 
    app: weschapdesafio06
  name: weschapdesafio06-service
  namespace: default
 
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: weschapdesafio06
